# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brows < Formula
  desc "Simple encrypted configuration management tool."
  homepage "https://github.com/rubysolo/brows"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.3/brows_darwin_amd64.tar.gz"
      sha256 "f78319b6bda8c4e7504e848ababa9534506a2ce95cd061d79857785218814aa1"

      define_method(:install) do
        bin.install "brows"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.3/brows_darwin_arm64.tar.gz"
      sha256 "7549904c887c18cffa5d81f620ae1fdff7bb35ab1f3264fa1cd10dc438805fce"

      define_method(:install) do
        bin.install "brows"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.3/brows_linux_amd64.tar.gz"
      sha256 "088e9f14f62f9564fda4b5a633810b4bb3316b2eb830d43f423ac2ef65feea5f"
      define_method(:install) do
        bin.install "brows"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.3/brows_linux_arm64.tar.gz"
      sha256 "14b196bf824db33d2c8437b18498bc775c180ec0258164a056d2a882d22ae1a9"
      define_method(:install) do
        bin.install "brows"
      end
    end
  end

  test do
    system "#{bin}/brows version"
  end
end
