# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brows < Formula
  desc "A CLI GitHub release browser"
  homepage "https://github.com/rubysolo/brows"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.2/brows_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ded3aa52070088a2962d01dce52816860373dd06e95a2332d80738dcf7904f69"

      def install
        bin.install "brows"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.2/brows_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "07bc3c6b872ba60509208d29af527b02020440e88e34bae11e528c3ee1300912"

      def install
        bin.install "brows"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.2/brows_0.1.2_Linux_x86_64.tar.gz"
      sha256 "67ac1ae693110290703037c64b3fd6d27e5a67bc8929b31df9d782dd6792b14f"

      def install
        bin.install "brows"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rubysolo/brows/releases/download/v0.1.2/brows_0.1.2_Linux_arm64.tar.gz"
      sha256 "856a9c3535737597ce7181567ddb57e642586ba12c4df6f2cc936a6576108769"

      def install
        bin.install "brows"
      end
    end
  end
end
